# Generated by Django 5.0.7 on 2024-08-05 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='한 줄 고민')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='고민 답변')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mentoring.concern')),
            ],
        ),
        migrations.CreateModel(
            name='ConcernInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.concern')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interest')),
            ],
        ),
        migrations.AddField(
            model_name='concern',
            name='interests',
            field=models.ManyToManyField(through='mentoring.ConcernInterest', to='users.interest'),
        ),
    ]
